version: '3.9'

services: 
  api: 
    image: cmtabr/api
    build: 
      context: ./api
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports: 
      - "5000:5000"
    volumes: 
      - ./:/app
    depends_on: 
      database:
        condition: service_healthy
    networks:
      - system

  database:
    image: cmtabr/database
    build: 
        context: ./database
        dockerfile: Dockerfile
    container_name: database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: banco
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - system

networks:
  system:
    driver: bridge