name: test

services:
  test:
    image: veritas/test
    build: 
      context: test
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 5000
    restart: on-failure
    ports: 
      - "5000-5001:5000"
    volumes:
      - ./test:/app:rw
    healthcheck:
      test: ["CMD", "curl", "-X", "GET", "http://test:5000/api/v1/healthcheck"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 5s
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '0.30'
          memory: 100M
        reservations:
          cpus: '0.10'
          memory: '40M'
  
  nginx:
    image: nginx:latest
    ports:
      - "3000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - test
