services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    volumes:
      - ../../volumes/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ../../volumes/grafana:/var/lib/grafana

volumes:
  prometheus:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./prometheus
  grafana:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./grafana
